### ISSUE TITLE
test: preserve daemon diagnostics on pre-health exit

### ISSUE THREAD

**Issue by NicholaiVogel** [Signet-AI/signetai#1519]
## Summary

The native embedding source-daemon test still reports macOS Intel startup failures as a blank stderr message even after #1516. That output is not sufficient to identify a daemon defect because the daemon's structured logger writes normal console output to stdout and its durable diagnostics to the agents-dir log and `.daemon/lifecycle.json`. The test currently discards stdout and reads neither artifact when startup fails.

## Evidence

- Nightly run: https://github.com/Signet-AI/signetai/actions/runs/31645765026
- macOS Intel job: https://github.com/Signet-AI/signetai/actions/runs/31645765026/job/94279128469
- The source-daemon test fails before `/health` with `daemon exited before health (status 1); stderr:` and an empty stderr section.
- Linux x64, Linux arm64, and macOS arm64 pass the same test in that run.
- Windows also passes the `/health` isolation scenario. Its job failure is the separate signal-portability issue tracked in #1518.

The test spawns the daemon with `stdio: ["ignore", "pipe", "pipe"]` but attaches handlers that discard both `child.stdout` and `child.stderr`. In the daemon implementation, structured logger console output uses `console.log`, while the logger resolves its file under `SIGNET_PATH/.daemon/logs`. The lifecycle implementation writes the terminal startup/error state to `SIGNET_PATH/.daemon/lifecycle.json`.

The local first run reproduced status 1 only because the fresh worktree had not built `@signet/core`; a direct child repro exposed `Cannot find module '@signet/core'`. After installing and building the workspace dependency, the test passed locally. CI already builds dependencies successfully, so that local failure is not the CI explanation.

## Impact

The current failure message hides the actual startup failure on macOS Intel. It is not valid evidence that a stalled native embedding worker caused a silent daemon exit. Without the child stdout, lifecycle record, and agents-dir log, the daemon-side root cause cannot be distinguished from a platform/runtime startup problem.

## Fix direction

On pre-health child exit, include bounded child stdout plus the child lifecycle record and relevant agents-dir log content in the failure. Preserve those diagnostics before cleanup, or retain the temporary agents directory on failure. Keep stderr capture from #1516. Then rerun macOS Intel before opening a P1 daemon issue.

Related: #1515, #1516, #1518, #1270, #1513.
